# Конфигурация ролей для системы контроля доступа
# Этот файл можно редактировать для изменения прав доступа без перезапуска приложения

roles:
  # ==================== РОЛИ ДЛЯ ЛЮДЕЙ ====================
  
  - role_name: guest
    entity_type: human
    description: "Гость с минимальными правами доступа"
    allowed_doc_types: null  # null = все типы
    allowed_visibility:
      - public
    max_security_level: 0
    allowed_departments: null
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
  
  - role_name: developer
    entity_type: human
    description: "Разработчик с доступом к техническим документам"
    allowed_doc_types:
      - technical_docs
      - work_plans
      - protocols
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 3
    allowed_departments:
      - engineering
      - product
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#3498db"
      icon: "💻"
  
  - role_name: senior_developer
    entity_type: human
    description: "Старший разработчик с расширенными правами"
    allowed_doc_types: null  # Видит все типы
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 4
    allowed_departments:
      - engineering
      - product
      - architecture
    can_create: true
    can_edit_own: true
    can_edit_others: true  # Может редактировать код-ревью и документацию
    can_delete_own: true
    can_delete_others: false
    can_manage_access: true
    metadata:
      color: "#2ecc71"
      icon: "👨‍💻"
  
  - role_name: business_analyst
    entity_type: human
    description: "Бизнес-аналитик с доступом к планам и аналитике"
    allowed_doc_types:
      - work_plans
      - presentations
      - email_correspondence
      - technical_docs
      - protocols
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 3
    allowed_departments:
      - product
      - business
      - engineering
      - analytics
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#9b59b6"
      icon: "📊"
  
  - role_name: technical_writer
    entity_type: human
    description: "Технический писатель для создания документации"
    allowed_doc_types:
      - technical_docs
      - protocols
      - presentations
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 2
    allowed_departments:
      - documentation
      - engineering
      - product
    can_create: true
    can_edit_own: true
    can_edit_others: true  # Может редактировать документацию других
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#e74c3c"
      icon: "✍️"
  
  - role_name: project_manager
    entity_type: human
    description: "Менеджер проектов с широким доступом"
    allowed_doc_types: null  # Видит все типы
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 4
    allowed_departments: null  # Доступ ко всем департаментам
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: true
    metadata:
      color: "#f39c12"
      icon: "📋"
  
  - role_name: designer
    entity_type: human
    description: "Дизайнер с доступом к презентациям и документации"
    allowed_doc_types:
      - presentations
      - technical_docs
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 2
    allowed_departments:
      - design
      - product
      - marketing
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#e91e63"
      icon: "🎨"
  
  - role_name: qa_engineer
    entity_type: human
    description: "QA инженер с доступом к тестовой документации"
    allowed_doc_types:
      - technical_docs
      - protocols
      - work_plans
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 3
    allowed_departments:
      - qa
      - engineering
      - product
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#00bcd4"
      icon: "🐛"
  
  - role_name: data_scientist
    entity_type: human
    description: "Data Scientist с доступом ко всем данным для анализа"
    allowed_doc_types: null  # Видит все
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 4
    allowed_departments:
      - data
      - analytics
      - engineering
      - business
    can_create: true
    can_edit_own: true
    can_edit_others: false
    can_delete_own: true
    can_delete_others: false
    can_manage_access: false
    metadata:
      color: "#009688"
      icon: "🔬"
  
  - role_name: admin
    entity_type: human
    description: "Администратор с полными правами"
    allowed_doc_types: null
    allowed_visibility:
      - public
      - team
      - channel
      - private
    max_security_level: 5
    allowed_departments: null
    can_create: true
    can_edit_own: true
    can_edit_others: true
    can_delete_own: true
    can_delete_others: true
    can_manage_access: true
    metadata:
      color: "#f44336"
      icon: "👑"
  
  # ==================== РОЛИ ДЛЯ БОТОВ/АГЕНТОВ ====================
  
  - role_name: agent_research
    entity_type: agent
    description: "Бот для исследований и поиска технической информации"
    allowed_doc_types:
      - technical_docs
      - work_plans
      - presentations
      - protocols
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 2
    allowed_departments: null
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 60
      can_stream: true
  
  - role_name: agent_support
    entity_type: agent
    description: "Бот поддержки для ответов на вопросы пользователей"
    allowed_doc_types:
      - protocols
      - technical_docs
      - email_correspondence
    allowed_visibility:
      - public
      - channel
    max_security_level: 1
    allowed_departments:
      - support
      - documentation
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 120
      can_stream: true
      response_timeout: 30
  
  - role_name: agent_analytics
    entity_type: agent
    description: "Бот аналитики с широким доступом для анализа данных"
    allowed_doc_types: null  # Видит все типы
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 3
    allowed_departments: null
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 30
      batch_processing: true
  
  - role_name: agent_summarizer
    entity_type: agent
    description: "Бот для суммаризации переписки и документов"
    allowed_doc_types:
      - email_correspondence
      - messenger_correspondence
      - work_plans
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 1
    allowed_departments: null
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 30
      can_stream: true
  
  - role_name: agent_code_review
    entity_type: agent
    description: "Бот для код-ревью с доступом к техническим документам"
    allowed_doc_types:
      - technical_docs
      - unstructured
    allowed_visibility:
      - public
      - team
      - channel
    max_security_level: 2
    allowed_departments:
      - engineering
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 30
      specialized: true
  
  - role_name: agent_admin
    entity_type: agent
    description: "Административный бот с полным доступом для мониторинга"
    allowed_doc_types: null
    allowed_visibility:
      - public
      - team
      - channel
      - private
    max_security_level: 5
    allowed_departments: null
    can_create: false
    can_edit_own: false
    can_edit_others: false
    can_delete_own: false
    can_delete_others: false
    can_manage_access: false
    metadata:
      max_requests_per_minute: 60
      monitoring: true

# Иерархия ролей (наследование прав)
role_inheritance:
  senior_developer:
    - developer
  project_manager:
    - business_analyst
  admin:
    - project_manager
    - senior_developer

